name: Main

on:
  push:
    branches:
    - main

jobs:
  npm-publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    if: contains( join( github.event.commits.*.message, ', ' ), '[ci release]' )

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm

    - name: Install dependencies
      run: |
        npm ci --no-progress

    - name: Get current version
      id: package-version
      run: |
        echo ::set-output name=current-version::$(cat ./package.json | jq '.version' | tr -d '"')

    - name: Build package
      run: |
        npm run build

    - name: "Tag latest commit"
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
        gh auth setup-git
        git config user.name "GitHub Actions"
        git tag "v${{ steps.package-version.outputs.current-version }}" -a -m "${{ github.event.commits[0].message }}"
        git push origin "v${{ steps.package-version.outputs.current-version }}"

    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        access: public
        token: ${{ secrets.NPM_TOKEN }}

    - name: Create GitHub release
      run: |
        gh release create --generate-notes "v${{ steps.package-version.outputs.current-version }}"
